package com.gayadi.android.navigation

object Routes {
    const val STARTUP = "startup"
    const val LOGIN = "login"
    const val BASIC_INFO = "basic_info"
    const val SURVEY = "survey"
    const val SURVEY_RESULT = "survey_result/{resultCode}"
    const val FRIEND_ADD = "friend_add"
    const val PLACE_SEARCH = "place_search/{tripId}"
    const val PLACE_DETAIL = "place_detail/{tripId}/{placeId}"
    const val MY_TRIP = "my_trip"
    const val TRIP_CREATE = "trip_create"
    const val TRIP_DETAIL = "trip_detail/{tripId}"
    const val TRIP_EDIT = "trip_edit/{tripId}"
    const val TRIP_PARTICIPANTS = "trip_participants/{tripId}"
    const val TRIP_INVITATION = "trip_invitation/{tripId}"
    const val TRIP_SCHEDULE = "trip_schedule/{tripId}"
    const val ROUTE_HUB = "route_hub/{tripId}"
    const val ROUTE_RECOMMENDATION = "route_recommendation/{tripId}/{routeType}"
    const val NEARBY_PLACES = "nearby_places/{tripId}?placeId={placeId}"
    const val FAVORITE_PLACES = "favorite_places/{tripId}"
    const val REALTIME_HOME = "realtime_home/{tripId}"
    const val MY_PAGE = "my_page"
    const val SETTINGS = "settings"
    const val MY_TRAVEL_PROFILE = "my_travel_profile"
    const val LEGAL_DOCUMENT = "legal_document/{documentId}"

    fun placeSearch(tripId: String) = "place_search/$tripId"
    fun placeDetail(tripId: String, placeId: String) = "place_detail/$tripId/$placeId"
    fun surveyResult(resultCode: String) = "survey_result/$resultCode"
    fun realtimeHome(tripId: String) = "realtime_home/$tripId"
    fun tripDetail(tripId: String) = "trip_detail/$tripId"
    fun tripEdit(tripId: String) = "trip_edit/$tripId"
    fun tripParticipants(tripId: String) = "trip_participants/$tripId"
    fun tripInvitation(tripId: String) = "trip_invitation/$tripId"
    fun tripSchedule(tripId: String) = "trip_schedule/$tripId"
    fun routeHub(tripId: String) = "route_hub/$tripId"
    fun routeRecommendation(tripId: String, routeType: String) = "route_recommendation/$tripId/$routeType"
    fun nearbyPlaces(tripId: String, placeId: String? = null) =
        if (placeId == null) "nearby_places/$tripId" else "nearby_places/$tripId?placeId=$placeId"
    fun favoritePlaces(tripId: String) = "favorite_places/$tripId"
    fun legalDocument(documentId: String) = "legal_document/$documentId"
}
